code --install-extension abusaidm.html-snippets^
  --install-extension ban.spellright^
  --install-extension bierner.markdown-preview-github-styles^
  --install-extension cweijan.vs-autohotkey-plus^
  --install-extension dracula-theme.theme-dracula^
  --install-extension esbenp.prettier-vs^
  --install-extension GrapeCity.gc-excelviewer^
  --install-extension Gruntfuggly.todo-tree^
  --install-extension kirozen.wordcounter^
  --install-extension mikestead.dotenv^
  --install-extension ms-azuretools.vs-docker^
  --install-extension ms-python.python^
  --install-extension ms-vs-remote.remote-wsl^
  --install-extension SimonSiefke.prettier-vs^
  --install-extension VisualStudioExptTeam.vs-intelli^
  --install-extension vs-vim.vim